export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_FIVE_DAYS_FORECAST = "GET_FIVE_DAYS_FORECAST";
export const ADD_TO_FAVORITE_LIST = "ADD_TO_FAVORITE_LIST";
export const REMOVE_FROM_FAVORITE_LIST = "REMOVE_FROM_FAVORITE_LIST";
export const ADD_FAVORITE_CURRENT_WEATHER = "ADD_FAVORITE_CURRENT_WEATHER";
export const NAVIGATE_TO_FAVORITE_SCREEN = "NAVIGATE_TO_FAVORITE_SCREEN";
export const NAVIGATE_TO_HOME_SCREEN = "NAVIGATE_TO_HOME_SCREEN";
